services:
  grafana:
    container_name: 'azure-data-explorer-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.0.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/azure-data-explorer-datasource
      - ./provisioning:/etc/grafana/provisioning
