version: '3.0'

services:
  grafana:
    container_name: 'azure-data-explorer-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.1.2}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/azure-data-explorer-datasource
      - ./provisioning:/etc/grafana/provisioning
