// This file is needed because it is used by vscode and other tools that
// call `jest` directly.  However, unless you are doing anything special
// do not edit this file

const standard = require('@grafana/toolkit/src/config/jest.plugin.config');
const config = standard.jestConfig();

// allows us to have our own custom set up test file
config.setupFilesAfterEnv = ['<rootDir>/src/test/setupTests.ts'];

// This process will use the same config that `yarn test` is using
// Including jsdom-sixteen to get the JSDOM v16 for Jest tests which is need for the react testing tools: https://github.com/testing-library/dom-testing-library/issues/477
module.exports = {
  ...config,
  testEnvironment: 'jest-environment-jsdom-sixteen',
  watchPathIgnorePatterns: ['<rootDir>/node_modules/'],
};
