name: E2E tests - Cypress
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: grafana/grafana-plugin-ci-e2e:1.9.3
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Initialise nvm
        run: |
          cp /root/.init-nvm.sh ~/.init-nvm.sh
          . ~/.init-nvm.sh

      - name: Install yarn dependencies
        run: yarn install
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Build
        run: go build -v ./...

      - name: Build Frontend
        run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Start Grafana
        run: docker run --rm -d -p 3000:3000 --name=grafana --env GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-azure-data-explorer-datasource --volume "$PWD:/var/lib/grafana/plugins" grafana/grafana

      - name: Run E2E tests
        run: yarn run e2e
        env:
          E2E_ADX_CLIENT_ID: ${{ secrets.E2E_ADX_CLIENT_ID }}
          E2E_ADX_CLIENT_SECRET: ${{ secrets.E2E_ADX_CLIENT_SECRET }}
          E2E_ADX_CLUSTER_URL: ${{ secrets.E2E_ADX_CLUSTER_URL }}
          E2E_ADX_TENANT_ID: ${{ secrets.E2E_ADX_TENANT_ID }}
