name: E2E tests - Cypress
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Install yarn dependencies
        run: yarn install
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Build
        run: go build -v ./...

      - name: Build Frontend
        run: yarn build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
      - name: Start Grafana
        run: docker run --rm -d -p 3000:3000 --name=grafana --env GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-azure-data-explorer-datasource --volume "$PWD:/var/lib/grafana/plugins" grafana/grafana
