name: Dependabot reviewer

on:
  pull_request:

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
      id-token: write  # required for get-vault-secrets action

    uses: grafana/security-github-actions/.github/workflows/dependabot-automerge.yaml@main
    with:
      repository-merge-method: squash
      packages-minor-autoupdate: '["@grafana/data","@grafana/ui","@grafana/runtime","@grafana/e2e","@grafana/e2e-selectors"]'
    secrets: inherit
