name: Verify i18n markup has been committed

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-i18n:
    uses: grafana/grafana-github-actions/.github/workflows/verify-i18n.yml@3cfd8aa18530171681eca2a3eb542721b8413418 # main
