name: Verify i18n markup has been committed

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify-i18n:
    permissions:
      contents: read
    uses: grafana/grafana-github-actions/.github/workflows/verify-i18n.yml@d227dc3a2a2f241c3e0ca3dbab103069ff979f9a # main
